[theme]
base = "light"

# General color setup
textColor = "#1a202c"
primaryColor = "#4318ff"
backgroundColor = "#f7fafc"
secondaryBackgroundColor = "#ffffff"

# Widgets
showWidgetBorder = true
borderColor = "#e2e8f0"

# Dataframes
dataframeHeaderBackgroundColor = "#f7fafc"

# Base text
font = "'DM Sans':https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600;700&display=swap"
baseFontWeight = 400
baseFontSize = 15

# Heading text
headingFont = "Poppins"
headingFontWeights = [700, 600, 600, 500, 500, 500]
headingFontSizes = ["2.6rem", "1.6rem", "1.2rem"]
