[theme]
base = "light"

# General color setup
textColor = "#1a1a1a"
primaryColor = "#dc2626"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"

# Widgets
showWidgetBorder = true
borderColor = "#dc2626"

# Dataframes
dataframeHeaderBackgroundColor = "#ffffff"

# Base text
font = "'Space Grotesk':https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap"
baseFontWeight = 300
baseFontSize = 14

# Heading text
headingFont = "Space Grotesk"
headingFontWeights = [300, 400, 400, 300, 300, 300]
headingFontSizes = ["2.5rem", "1.5rem", "1rem"]
